#!/usr/bin/env bash

# Script: install_load_balancer
# Description: Installs and configures the HAProxy load balancer
# Author: [Your Name]
# Date: [Date]

# Update the package repository
sudo apt-get -y update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy service
sudo sed -i "9i ENABLED=1" /etc/default/haproxy

# Configure HAProxy
sudo cat >> /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
  bind *:80
  mode http
  default_backend web_server

backend web_server
  mode http
  balance roundrobin
  server 510493-web-01 52.204.78.39:80 check
  server 510493-web-02 54.157.140.148:80 check
EOF

# Restart HAProxy service
sudo service haproxy restart
